import { chromium } from '@playwright/test';
const out = process.argv[2];
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; p.on('pageerror', (e) => errors.push(String(e)));
await p.goto('http://localhost:5190/admin/login');
await p.getByLabel('E-mail').fill('admin@example.com'); await p.getByLabel('Senha').fill('palace-dev-12345');
await p.getByRole('button', { name: 'Entrar' }).click(); await p.getByRole('heading', { name: 'Painel', exact: true }).waitFor();
await p.goto('http://localhost:5190/admin/pedidos', { waitUntil: 'networkidle' });
await p.locator('tbody a').first().click(); await p.getByText('Próximo passo').waitFor();
await p.getByRole('button', { name: 'Cancelar pedido' }).click({ trial: true });
await p.screenshot({ path: out + '/order.png', fullPage: true });
await p.goto('http://localhost:5190/admin', { waitUntil: 'networkidle' }); await p.screenshot({ path: out + '/dash.png', fullPage: true });
console.log(JSON.stringify(errors)); await b.close();
