-- Bloqueia o acesso às tabelas pela API REST automática do Supabase (PostgREST com
-- chaves anon/authenticated). Sem políticas, nenhuma linha é visível por esse caminho.
-- A commerce-api conecta como dono das tabelas e não é afetada (o dono ignora RLS
-- quando ela não é FORCE). O isolamento entre lojas continua sendo feito pela API.
ALTER TABLE "Address" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Catalog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CatalogLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CatalogProduct" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FinanceCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderStatusHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
